# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  release:
    docker:
      - image: circleci/python:latest
    steps:
      - attach_workspace:
          at: /tmp/build
      - run:
          name: "Setup env vars"
          command: |
            echo "export AWS_ACCESS_KEY_ID=$AWS_LAMBDA_ACCESS_KEY" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_LAMBDA_ACCESS_KEY" >> $BASH_ENV
      - run: echo $AWS_ACCESS_KEY_ID $AWS_REGION
      - aws-s3/copy:
          from: /tmp/build/build/dist.zip
          to: 's3://miguelet-audios/GetMigueletQuoteCode'
      - run: aws lambda update-function-code --function-name GetMigueletQuote --s3-bucket miguelet-audios --s3-key GetMigueletQuoteCode --publish

workflows:
  version: 2
  build_and_deploy_lambda:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: primary
      - release:
          filters:
            branches:
              only: primary
          requires:
            - build
